version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "replymint-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "replymint-staging"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging LogRetentionDays=14"
image_repositories = []

[default.build]
[default.build.parameters]
use_container = false
cached = true
parallel = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "replymint-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "replymint-prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod LogRetentionDays=30"
image_repositories = []

[prod.build]
[prod.build.parameters]
use_container = false
cached = true
parallel = true
